version: "1.1"
pipeline:
  name: bodywork-aporia
  docker_image: bodyworkml/bodywork-core:latest
  DAG: serve-model
  secrets-group: prod
stages:
  serve-model:
    executable_module_path: pipeline/serve_model.py
    args:
      - "--aporia-model-id=bodywork-model2"
      - "--aporia-model-version=v1"
    requirements:
      - joblib==1.0.1
      - numpy==1.21.0
      - scikit-learn==0.24.2
      - fastapi==0.65.2
      - uvicorn==0.14.0
      - aporia==1.0.59
    cpu_request: 0.5
    memory_request_mb: 100
    service:
      max_startup_time_seconds: 180
      replicas: 1
      port: 8000
      ingress: true
    secrets:
      APORIA_HOST: aporia
      APORIA_TOKEN: aporia
      APORIA_ENVIRONMENT: aporia
logging:
  log_level: INFO
